apiVersion: v1
kind: Service
metadata:
  name: simple-app-svc
  labels:
    run: simple-app-svc
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    run: simple-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-app
spec:
  selector:
    matchLabels:
      run: simple-app
  replicas: 1
  template:
    metadata:
      labels:
        run: simple-app
    spec:
      containers:
        - name: simple-app
          image: washraf/simple-app
          ports:
            - containerPort: 80

